### ISSUE TITLE
Not able to publish using a windows system. 

### ISSUE THREAD

**Issue by sanjanaadeshra** [opencomponents/oc#1038]
I am not able to publish components using a windows system. 

Node version - 10.x.x
oc version - 0.47.0

**Comment by eksted** [comment]
I have a same proplem.
If modify cli/facade/publish.js ->  method: putComponentToRegistry and show options.path in log. 
can get "C:\\OC\\my-component\\package.tar.gz", but package.tar.gz not exists

**Comment by eksted** [comment]
heroku response: {"error":"package is not valid","details":{"errno":-13,"code":"EACCES","syscall":"mkdir","path":"/app/temp/package-1558610647276/_package/css"}}

**Comment by matteofigus** [comment]
Actually closing as this seems to be a duplicate of https://github.com/opencomponents/oc/issues/819
