### ISSUE TITLE
Security vulnerabilities in oc package dependencies

### ISSUE THREAD

**Issue by arnaugm** [opencomponents/oc#1176]
## *Who* is the bug affecting?

Any user of the `oc` package.

## *What* is affected by this bug?

Projects using the `oc` package as a dependency and running a Snyk test or `npm audit` will see several security vulnerabilities coming from dependencies of this package.

## *When* does this occur?

On running a Snyk security test or `npm audit`.

## *Where* on the platform does it happen?

In clients of the oc package.

## *How* do we replicate the issue?

Snyk:
```
snyk test --dev --prune-repeated-subdependencies
```
NPM:
```
npm audit
```

## Expected behavior (i.e. solution)

The package should be free of security vulnerabilities

## What version of OC, Node.js and OS are you using?

**oc:** 0.48.15
**node:** v12.19.0
**OS:** macOS Catalina 10.15.6

## Other Comments
Last version of oc package, `0.48.15` suffers from several vulnerability issues in its dependencies.
They are visible through `npm audit` or by using Snyk.
Important to note that some come from deprecated packages like `oc-template-handlebars`.

![oc-security](https://user-images.githubusercontent.com/1050567/101766216-c4943800-3ae2-11eb-8ec0-1f53a9e2db74.jpg)
![oc-security2](https://user-images.githubusercontent.com/1050567/101766226-c9f18280-3ae2-11eb-81dc-1e7e5722f060.jpg)
![oc-security3](https://user-images.githubusercontent.com/1050567/101766240-ce1da000-3ae2-11eb-8277-fe6b116a4d97.jpg)

**Comment by matteofigus** [comment]
@chriscartlidge @dipunm I know you were working on the handlebars stuff, any progress with that?

**Comment by arnaugm** [comment]
hi @matteofigus the situation didn't change since December last year, do you have any update on this?

**Comment by ricardo-devis-agullo** [comment]
Those vulnerabilities should be gone now, so I'm closing this.
