### ISSUE TITLE
Moving from callback-based to promises

### ISSUE THREAD

**Issue by ricardo-devis-agullo** [opencomponents/oc#1208]
Not really an important change, but would be nice to move all the callback-styled code to Promises async/await style. Of course, because oc is composed of multiple packages and they all depend on callback based interfaces, this can't be done in one go (technically yes by updating majors but a bit of a nightmare), so a sensible approach could be to convert all internal callbacks to promises, and on the external surface (those functions exported by the library), use something like [universalify](https://www.npmjs.com/package/universalify) so those can work both with callback or promises depending if you pass a function as last parameter (so we can have a gradual refactor)

**Comment by matteofigus** [comment]
I like the idea. I also think that at this point if we are approaching v1 I would rather go opinionated (for instance async/await only) rather than to keep supporting the cb style - but this is just my 2 cents.

**Comment by ricardo-devis-agullo** [comment]
Makes sense to me, we can start by moving to promises with universalify fallback, and remove the fallback on 1.0 (upgrading major on all the rest of packages).
