### ISSUE TITLE
Accessing IP of the user inside our OC

### ISSUE THREAD

**Issue by milos-ponj** [opencomponents/oc#1211]
Our business needs functionality in which we record IP of the user who interacts with the OC. During my research I've encountered 
_oc-free-geo-ip-plugin_ which suggests following code should get the IP:

`const ip = context.requestHeaders['x-forwarded-for'] || context.requestHeaders.remoteAddress;`

But is there a way to get it inside the OC itself? After talking with @ricardo-devis-agullo it seems remoteAddress doesn't even exist on context.requestHeaders so the copied code would only work if the 'x-forwarded-for' header is provided by the server.

**Comment by ricardo-devis-agullo** [comment]
So I guess we could add a new `ip` property to the context object that could be something like
`ip: req.ip || req.headers['x-forwarded-for'] || req.connection.remoteAddress`
