### ISSUE TITLE
Adding a new bin option for running the OC CLI tool

### ISSUE THREAD

**Issue by fbarbare** [opencomponents/oc#1281]
Adding a new bin option for running the OC CLI tool as `oc` can already be used by other CLIs

## _Who_ is the bug affecting?

Component creators

## _What_ is affected by this bug?

node client

## _When_ does this occur?

When trying to run an `oc` command using `npx`

## _Where_ on the platform does it happen?

CLI

## _How_ do we replicate the issue?

1. Run `npx oc package` on an Ubuntu machine that has the Red Hat OpenShift CLI installed

## Expected behavior (i.e. solution)

It should have run the `package` command of the OpenComponent library

## What version of OC, Node.js and OS are you using?

OC@0.49.4
Node@16.13.0
npm > 7

## Other Comments

We could add a `open-components` option in the `bin` of `the package.json` so we can ensure it does not conflict with other CLI tools

We were working around this issue by using the `--ignore-existing` argument on the `npx` command, but this has been removed since npm@7

**Comment by ricardo-devis-agullo** [comment]
looks good to me

**Comment by fbarbare** [comment]
I'll create a PR then

**Comment by ricardo-devis-agullo** [comment]
not sure this is doable, so closing it
