### ISSUE TITLE
Console is not fully defined in production

### ISSUE THREAD

**Issue by mungodewar** [opencomponents/oc#1316]
## _Who_ is the bug affecting?

Component authors/creators.

## _What_ is affected by this bug?

The ability to server-side render components.

## _When_ does this occur?

When trying to server render a component in production.

## _Where_ on the platform does it happen?

In the registry in production only. This issue is not present locally as the "real" console object is passed into the `vm` context. This makes this problem particularly dangerous.

## _How_ do we replicate the issue?

1. Add `console.warn` anywhere inside `server.js`. 
2. Build component and run inside production (non-local) registry.
3. Observe `console.warn is not a function` error when trying to fetch/get component from registry.

## Expected behavior (i.e. solution)

`console` api should be fully stubbed inside component server execution. I've drafted a PR: https://github.com/opencomponents/oc/pull/1315 that I hope details what I think should happen.

## What version of OC, Node.js and OS are you using?

oc@0.49.6
node@16.18.1

**Comment by ricardo-devis-agullo** [comment]
Why would you want to use console.warn inside server.js, anyways, since OC is going to ignore all messages?

**Comment by mungodewar** [comment]
> Why would you want to use console.warn inside server.js, anyways, since OC is going to ignore all messages?

This is just an demo example of triggering the bug. What is really happening is a deep dependency within the react render tree is using a `console.warn` statement. IMO usage of `console.warn` this shouldn't stop the component rendering correctly within the oc-registry context.

**Comment by mungodewar** [comment]
> Got it. LGTM then.

I'll update my PR to your suggested change.
