### ISSUE TITLE
oc-s3-storage-adapter 2.1.1 not working with IAM roles

### ISSUE THREAD

**Issue by ashmeet-kandhari** [opencomponents/oc#1322]
## _Who_ is the bug affecting?

All

## _What_ is affected by this bug?
OC Registry startup

## _When_ does this occur?

During the oc registry startup

## _Where_ on the platform does it happen?

AWS Environment when trying to use IAM roles instead of passing secret and access keys

## _How_ do we replicate the issue?

1. Deploy OC 0.49.23 v service in AWS environment without passing AWS access and secret keys and only dependent on IAM roles attached
2. The startup would fail.

## Expected behavior (i.e. solution)

S3 Client should have picked up IAM role using credsProviderChain internally. And the registry should have started 

## What version of OC, Node.js and OS are you using?

OC@0.49.23, Node 16.4.0, Linux

## Other Comments
The issue is the oc-s3-storage-adapter actually passes credentials object even if AWS accesskeys and secret keys are not passed.

I have created patch file for this fix
```--- node_modules/oc-s3-storage-adapter/lib/index.js	2023-01-13 12:09:03.000000000 +0000
+++ oc-s3-storage-adapter/index.js	2023-01-13 14:25:07.000000000 +0000
@@ -20,6 +20,7 @@
     stream.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
 });
 function s3Adapter(conf) {
+    console.log('Using patched oc-s3-storage-adapter');
     const isValid = () => {
         if (!conf.bucket ||
             !conf.region ||
@@ -53,18 +54,25 @@
         }
         requestHandler = new node_http_handler_1.NodeHttpHandler(handlerOptions);
     }
-    const getClient = () => new client_s3_1.S3({
-        logger: conf.debug ? console.log : undefined,
-        tls: sslEnabled,
-        credentials: {
-            accessKeyId: accessKeyId,
-            secretAccessKey: secretAccessKey
-        },
-        requestHandler,
-        endpoint: conf.endpoint,
-        region,
-        forcePathStyle: s3ForcePathStyle
-    });
+    const getClient = () => {
+        const configOpts = {
+            logger: conf.debug ? console.log : undefined,
+            tls: sslEnabled,
+            requestHandler,
+            endpoint: conf.endpoint,
+            region,
+            forcePathStyle: s3ForcePathStyle
+        }
+        // patch to fix credentials config only when both accessKeyId and secretAccessKey are present. 
+        if(accessKeyId && secretAccessKey){
+            configOpts.credentials = {
+                accessKeyId,
+                secretAccessKey
+            };
+        }
+
+        return new client_s3_1.S3(configOpts);
+    };
     const getFile = async (filePath, force = false) => {
         const getFromAws = async () => {
             try {
```

**Comment by ashmeet-kandhari** [comment]
If the patch fix looks, good I am happy to raise a PR for the same

**Comment by ricardo-devis-agullo** [comment]
Looks good to me, make a PR if you can please :)

**Comment by ashmeet-kandhari** [comment]
hi @ricardo-devis-agullo 

I have raised a PR.

**Comment by ashmeet-kandhari** [comment]
Hi @ricardo-devis-agullo 
Any update related to this?

**Comment by ricardo-devis-agullo** [comment]
merged!
