### ISSUE TITLE
Pacakage subpath ./runtime not defined

### ISSUE THREAD

**Issue by e-camp** [opencomponents/oc#1370]
## _Who_ is the bug affecting?

Anyone wanting to test a component/building without modifying package exports

## _What_ is affected by this bug?

Cannot test component

## _When_ does this occur?

When testing a component 

`an error happened while packaging /../hello-world: Package subpath './runtime' is not defined by "exports" in /../hello-world/node_modules/vite/package.json imported from /../hello-world/node_modules/oc-vite/dist/node/index.js`

## _Where_ on the platform does it happen?

CLI

## _How_ do we replicate the issue?

npm install oc -g
oc init hello-world
oc dev . 3030

## Expected behavior (i.e. solution)

test component should launch

## What version of OC, Node.js and OS are you using?

Tried on most current( v0.49.55 ) OC both Windows and OSX

**Comment by ricardo-devis-agullo** [comment]
Hi, this should be fixed now, although remember that the proper steps would be 

npm install oc -g
oc init hello-world
cd hello-world
nom install
cd ..
oc dev . 3030

**Comment by e-camp** [comment]
@ricardo-devis-agullo thank you!
