### ISSUE TITLE
Update Documentation to point to new organizations and general improvements

### ISSUE THREAD

**Issue by nickbalestra** [opencomponents/oc#504]
Now that we have https://github.com/opencomponents organization will be good if we point to that in the readme and wiki.

For general improvements [here](https://github.com/cyclejs/cyclejs/blob/master/README.md) some very good examples of readme to help with on-boarding and adoptions. I really dig the way he direct to Gitter, contributions, documentation ecc...

**Comment by matteofigus** [comment]
I think it's a good idea. I would like to convert the whole https://github.com/opentable/oc#links section to the cycle's table for contributing/help/etc..

**Comment by matteofigus** [comment]
Closing as we moved all the links to point to the new docs and the README will be reworked as part of V1 release
