### ISSUE TITLE
reusable OC eslint config

### ISSUE THREAD

**Issue by nickbalestra** [opencomponents/oc#518]
I was thinking that we could extract the [eslint config file ](https://github.com/opentable/oc/blob/master/.eslintrc.json) into his own module so that we can easily reuse this across any OC related repo in the form of [eslint extends](http://eslint.org/docs/user-guide/configuring#extending-configuration-files).

This because we now have the @opencomponents organization and quite few repos, and it would help keeping this config in a single place making it easier for others to conform and to clean-this as we move along.

@elboletaire @mattiaerre  what you think?

**Comment by mattiaerre** [comment]
@nickbalestra I think this is a very good idea; shall we inherit from a common one such us the Airbnb one and extend it w/ our rules or you think we should start w/ the one you linked above? what kind of rules would we like to have in place in general? I am personally happy w/ the Airbnb one to which I add 2 or 3 rules (maximum) on top.

**Comment by ricardo-devis-agullo** [comment]
I think adding Prettier removes the need of specific eslint rules about styling, and eslint and typescript recommended eslint settings take care of the rest.
