### ISSUE TITLE
Publishing components from Windows results in "An error happened when publishing the component: package is not valid"

### ISSUE THREAD

**Issue by catt231** [opencomponents/oc#819]
## *Who* is the bug affecting?
Windows Users

## *What* is affected by this bug?
Publishing components

## *When* does this occur?
oc publish my-component my-registry results in "An error happened when publishing the component: package is not valid"

## *Where* on the platform does it happen?
CLI

## *How* do we replicate the issue?
install oc
init component
add registry
try to publish to repo

## Expected behaviour (i.e. solution)
component should be published to repo

## What version of OC, Node.js and OS are you using?
OC 0.42.19
Node 9.3.0
Windows 10

## Other Comments
Have successfully followed the above steps and published from a Mac, Have also followed the same steps from a windows 10 VM to make sure it wasn't machine specific. 

Copied the tar.gz file from Windows to Mac - there seems to be some permissions issues opening the file - this may be the underlying issue?

**Comment by marcilio9590** [comment]
up

**Comment by ricardo-devis-agullo** [comment]
this should have been fixed by #1166
