### ISSUE TITLE
Author filter in registry page

### ISSUE THREAD

**Issue by jankowiakmaria** [opencomponents/oc#824]
Not an issue - rather a feature to be able to filter not only by component's name but by the author as well.

I've done a little bit of work already (but haven't finished yet).

Looks like:
![image](https://user-images.githubusercontent.com/6817645/35770782-d9f29672-0919-11e8-91aa-623826c9142e.png)

And after typing in something:
![image](https://user-images.githubusercontent.com/6817645/35770850-2b6d7dd6-091b-11e8-8af9-9d4c715216e5.png)

Any comments? Yay or nay?

**Comment by matteofigus** [comment]
Yay for me! 🥇
