### ISSUE TITLE
unable to set a cookie's path to '/'

### ISSUE THREAD

**Issue by benbotwin** [opencomponents/oc#906]
## *What* is affected by this bug?
browser client

## *When* does this occur?
any time a cookie is made

## *Where* on the platform does it happen?
clients

## *How* do we replicate the issue?
create a cookie with a path such as
`document.cookie = name='ben';path=/;`

## Expected behavior (i.e. solution)
The cookie's path should be `/`

## What version of OC, Node.js and OS are you using?
node 8.9.4
osx 10.13.4

## Other Comments
It seems like the cookie's path is always being set to whatever page the OC is on and not the root of the whole site, even when i set the cookies path to something like `path=http://mysiteisawe.some/`

**Comment by benbotwin** [comment]
I don't mind having the host portion there, but the rest of the URL is what i don't want. 
I'll set path to `/` and the cookie's path will end up being `/foo/bar/` or something like that which is the URI for for the page that's importing the OC.

Setting domain doesn't help, unfortunately.

**Comment by kmcrawford** [comment]
@benbotwin I am closing this issue.  Please work with K2 internally as this is being executed clientside and not an issue with oc.
