### ISSUE TITLE
"TEMPLATE_NOT_SUPPORTED" when creating new react component

### ISSUE THREAD

**Issue by avihaymenahem** [opencomponents/oc#921]
## *Who* is the bug affecting?
React Components

## *What* is affected by this bug?
Browser, supplied apps

## *When* does this occur?
on creating

## *Where* on the platform does it happen?
Client

## *How* do we replicate the issue?
new react template

## Expected behavior (i.e. solution)
should work :)

## What version of OC, Node.js and OS are you using?
OC@0.44.12, Mac OSX @10.13.6

## Other Comments
This is what im getting when setting new component:
```
{
"code": "TEMPLATE_NOT_SUPPORTED",
"error": "oc-template-react is not a supported oc-template",
"name": "app-header",
"requestVersion": "1.0.0"
}
```

**Comment by avihaymenahem** [comment]
Ok, i found it hidden in the docs, needed to add it manually to the conf when initializing the templates section:
```
{
                    "type": "oc-template-react",
                    "externals": [
                        {
                            "global" : "react",
                            "url" : "https://unpkg.com/react@16.0.0/umd/react.production.min.js"
                        }
                    ]
                }
```

**Comment by matteofigus** [comment]
@avihaymenahem I think you are right, the instructions for using custom templates are a bit unclear.

One thing you can do though is to curl your registry //your-registry/oc-client and look at al the html you see there. That should be the thing to put on each page (or you can setup a server side render of that OC on each page which is what most people do).
