### ISSUE TITLE
oc package <componentPath> does not find modules in componentPath

### ISSUE THREAD

**Issue by NimaSoroush** [opencomponents/oc#943]
## *Who* is the bug affecting?
component creators

## *What* is affected by this bug?
oc cli tool

## *When* does this occur?
When packaging component

## *Where* on the platform does it happen?
cli

## *How* do we replicate the issue?
- npm install -g oc@0.44.13
- Create an OC component (e.g. temp-oc)
- npm install in temp-oc root
- npm build temp-oc
- cd ..
- oc package ./temp-oc
- see the error
```
Packaging -> /Users/x/components/temp-oc/_package
Ensuring dependencies are loaded...
Trying to install missing modules: foo@^1.3.21, bar@^0.1.0
If you aren't connected to the internet, or npm isn't configured then this step will fail...FAIL
```

Note: `foo` and `bar` are installed through internal npm artifact

### working example
- npm install -g oc@0.44.13
- Create an OC component (e.g. temp-oc)
- npm install in temp-oc root
- npm build temp-oc
- oc package .
- output:
```
Packaging -> /Users/x/components/temp-oc/_package
Ensuring dependencies are loaded...
Packaged -> /Users/x/components/temp-oc/_package
```

## Expected behavior (i.e. solution)
oc package <componentPath> should respect node_modules instaled in `componentPath/node_modules`

## What version of OC, Node.js and OS are you using?
oc@0.44.13, Node v8.11.1, Mac

## Other Comments
possibly problem comes from this line
https://github.com/opencomponents/oc/blob/efeadfbfda5413080e7e908f112e20c71bb9f311/src/cli/facade/package.js#L21

**Comment by matteofigus** [comment]
@NimaSoroush I guess I should try to reproduce, but I seem to remember that that is respected for devDependencies, but dependencies are instead installed as root (to kind of replicate the behaviour of the real oc registry that actually uses global deps but locally bundled dev ones). Out of curiosity, are your `foo` and `bar` devDependencies or dependencies?

Thanks

**Comment by NimaSoroush** [comment]
@matteofigus : I see the point of replicating real oc registry but seems to be a bit of overhead as those packages are already installed for that component. Reinstalling it just cause more network call and makes the release process longer. Also, cause a particular issue with the setup we have. We have a CI plugin which package and publish OCs to oc registry and doesn't know anything about internal npm registry (our internal npm registry needs authentication to access packages). This means it will fail reinstalling `dependencies` of OC when packaging it.

In my opinion the behaviour can stay as is but should be controlled by a flag to enable/disable:

```
oc package <componentPath> --disable-installing-dependencies
```
or something similar, and when that flag passed it should just respect the `node_modules` in `componentPath/node_modules`

Also to answer your question:
> Out of curiosity, are your foo and bar devDependencies or dependencies?

yes, `foo` and `bar` are dependencies

**Comment by matteofigus** [comment]
Thanks for the feedback @NimaSoroush. I agree this is very far from ideal, in fact, we started working on a new branch for completely changing the dependency management (which is the main thing holding us from v1 release as we are all not very happy about it).

Your proposal (add a param to skip the npm installs) seems a neat thing to have anyways, I think I would love something like that. Would you be able to contribute with a PR for that?

**Comment by NimaSoroush** [comment]
Thanks @matteofigus : Can't wait for v1 anyway :)

Yeah. I might be able to Just add a PR for fixing it. Will update here when I have something in place
