### ISSUE TITLE
react-app-polyfill cannot be added as dependency

### ISSUE THREAD

**Issue by elboletaire** [opencomponents/oc#964]
## *Who* is the bug affecting?
Anyone trying to package an open component with the dependency `react-app-polyfill`

## *What* is affected by this bug?
The client, with any template (I've tried with handlebars and react templates).

## *When* does this occur?
When you try to package or run a dev server, packaging fails with a `FAIL` (no more errors).

## *Where* on the platform does it happen?
It's something with dependencies management, on the CLI.

## *How* do we replicate the issue?
1. Install oc globally: `npm i -g oc`
2. Create a new repo with the react template: `oc init my-awesome-repo oc-template-react`
3. Inside the repo, add the package `react-app-polyfill` as dependency: `npm add --save react-app-polyfill`
4. Go outside the repo and try to init a dev server, or simply to package the project: `oc dev . 3030`

![imatge](https://user-images.githubusercontent.com/153305/48358972-3dbec800-e69c-11e8-8d54-37c7de8dd4b3.png)

## Expected behavior (i.e. solution)
App should build or, at least, show a more specific error (right now just fails with a `FAIL` and nothing else, even if verbosity is enabled).

## What version of OC, Node.js and OS are you using?
- OC: From 0.43.1 to current version (0.45.0)
- NodeJS: From 6 to 8
- OS: Ubuntu Linux

**Comment by MattShrider** [comment]
This is a necro at this point, but i'm also running into this issue. Did you ever resolve it?

**Comment by elboletaire** [comment]
No, I wasn't able. But the way we were using OC enabled us to make a workaround. We weren't really using the OC build capabilities, instead, we pre-built our widgets in the CI pipeline with all the required files, and then we did publish those files to OC. So, to avoid the issue, what we did was move the problematic packages to the `devDependencies` block, this way they were ignored by OC.

Obviously it is not an option if you do use the OC building capabilities.

**Comment by ricardo-devis-agullo** [comment]
It's failing because OC tries to check that the module is installed by doing a [try-require](https://www.npmjs.com/package/try-require), but `react-app-polyfill` does not have an entry point defined, so the try-require fails and OC determines that the package wasn't installed in the `node_modules`, even though it was actually installed.
