### ISSUE TITLE
Edge-Side-Includes

### ISSUE THREAD

**Issue by lukebarton** [opencomponents/oc#972]
A great way of using oc could be to leverage [Edge-Side-Includes](https://en.wikipedia.org/wiki/Edge_Side_Includes) which are supported by Akamai and Cloudflare for example. To make this a possibility, you'd need a way of fetching the raw rendered html from the registry by URL only. 

e.g. 
```
<esi:include src="https://my-components-registry.mydomain.com/hello-world/1.0.0/~rendered" />
```

**Comment by mattiaerre** [comment]
this is an interesting idea @lukebarton would you like to spike it in a PR?
happy to help you w/ that

**Comment by lukebarton** [comment]
Thanks for the invitation but I'm not really convinced about the utility of Open Components in general, so at the moment I'd rather spend my energies elsewhere

**Comment by matteofigus** [comment]
Hi friends, AFAIK there is nothing blocking you today to use that tag via the ES6 template and with SSR, so I am closing because this should be already possible.
